version: "3.8"

services:
  auth-service:
    build: .
    container_name: auth_service
    restart: always
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/projectDB
      - JWT_SECRET=your_jwt_secret
      - PORT=5002
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
