version: '3'

services:
  # Service pour l'app
  backend:
    build: .
    ports:
      - "5000:5000"  # Mappe le port 5000 de l'hôte au port 5000 du conteneur
    environment:
      - MONGO_URI=mongodb://mongo:27017/projectdb  # Connexion MongoDB via mongo
    depends_on:
      - mongo  # Assure-toi que MongoDB est démarré avant l'application backend
    volumes:
      - .:/app  # Lier le répertoire local à /app dans le conteneur pour un développement fluide

  # Service pour MongoDB
  mongo:
    image: mongo  # Utilise l'image officielle de MongoDB
    ports:
      - "27017:27017"  # Mappe le port 27017 du conteneur au port 27017 de l'hôte
    volumes:
      - mongo-data:/data/db  # Persister les données dans un volume Docker nommé

# Volumes pour persister les données MongoDB
volumes:
  mongo-data: